[theme]
base = "dark"
primaryColor = "#3b82f6"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#f0f4ff"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
